"""Regenerate tarjuman/_units_table.py from the canonical NeuroML2 LEMS definitions.

Usage:
    python tools/generate_units_table.py path/to/NeuroML2CoreTypes/NeuroMLCoreDimensions.xml
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HEADER = '''"""Unit and dimension tables for NeuroML 2 / LEMS.

AUTO-GENERATED by ``tools/generate_units_table.py`` from the canonical
``NeuroMLCoreDimensions.xml`` shipped with the NeuroML2 repository.
Do not edit by hand.

Each entry maps a LEMS unit symbol to ``(dimension, scale, offset)`` such that

    value_in_SI = value_in_unit * scale + offset
"""

from __future__ import annotations

# dimension name -> {m, l, t, i, k, n} exponents
DIMENSIONS: dict[str, dict[str, int]] = {
'''


def main(path: str) -> None:
    root = ET.parse(path).getroot()
    ns = ""
    if root.tag.startswith("{"):
        ns = root.tag.split("}")[0] + "}"

    dims: dict[str, dict[str, int]] = {}
    for d in root.iter(f"{ns}Dimension"):
        name = d.get("name")
        dims[name] = {
            k: int(d.get(k))
            for k in ("m", "l", "t", "i", "k", "n")
            if d.get(k) is not None
        }

    units: dict[str, tuple[str, float, float]] = {}
    for u in root.iter(f"{ns}Unit"):
        symbol = u.get("symbol")
        dimension = u.get("dimension")
        power = int(u.get("power", "0"))
        scale = float(u.get("scale", "1"))
        offset = float(u.get("offset", "0"))
        units[symbol] = (dimension, scale * (10.0**power), offset)

    out = [HEADER]
    for name, exps in sorted(dims.items()):
        out.append(f"    {name!r}: {exps!r},\n")
    out.append("}\n\n\n")
    out.append("# unit symbol -> (dimension, scale, offset); SI = value * scale + offset\n")
    out.append("UNITS: dict[str, tuple[str, float, float]] = {\n")
    for symbol, (dimension, scale, offset) in sorted(units.items()):
        out.append(f"    {symbol!r}: ({dimension!r}, {scale!r}, {offset!r}),\n")
    out.append("}\n")

    target = Path(__file__).resolve().parent.parent / "tarjuman" / "_units_table.py"
    target.write_text("".join(out))
    print(f"wrote {target} ({len(dims)} dimensions, {len(units)} units)")


if __name__ == "__main__":
    main(sys.argv[1])
